#!/bin/sh

# PROVIDE: MtcCoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# MtcCoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable MtcCoin service.
# MtcCoin_config (path): Set to /usr/local/etc/MtcCoin.conf by default.
# MtcCoin_user:  The user account MtcCoin daemon runs as. It uses 'root' user by default.
# MtcCoin_group: The group account MtcCoin daemon runs as. It uses 'wheel' group by default.
# MtcCoin_datadir (str): Default to "/var/db/MtcCoin". Base data directory.

. /etc/rc.subr

name=MtcCoin
rcvar=MtcCoin_enable

: ${MtcCoin_enable:=NO}
: ${MtcCoin_config=/usr/local/etc/MtcCoin.conf}
: ${MtcCoin_datadir=/var/db/MtcCoin}
: ${MtcCoin_user="root"}
: ${MtcCoin_group="wheel"}

required_files=${MtcCoin_config}
command=/usr/local/bin/MtcCoind
MtcCoin_chdir=${MtcCoin_datadir}
pidfile="${MtcCoin_datadir}/MtcCoind.pid"
stop_cmd=MtcCoin_stop
command_args="-conf=${MtcCoin_config} -datadir=${MtcCoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

MtcCoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${MtcCoin_datadir}
	[ $? -eq 0 ] && chown -R ${MtcCoin_user}:${MtcCoin_group} ${MtcCoin_datadir}
}

MtcCoin_prestart()
{
	if [ ! -d "${MtcCoin_datadir}/." ]; then
		MtcCoin_create_datadir || return 1
	fi
}

MtcCoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

MtcCoin_stop()
{
    MtcCoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${MtcCoin_config} -datadir=${MtcCoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
